nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['']
        allow_headers: ['']
        allow_methods: ['POST','GET','DELETE','PUT', 'OPTIONS']
        expose_headers: ['*']
        max_age: 0
    paths:
        '^/':
            origin_regex: true
            allow_origin: [ '^http://localhost/:[0-9]+' , '*']
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600